# Generated by Django 3.0.8 on 2020-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='asset',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
